// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assetproto.proto

package assetproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAssetReq struct {
	Caption              string   `protobuf:"bytes,1,opt,name=caption" json:"caption,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	AssetType            string   `protobuf:"bytes,3,opt,name=asset_type,json=assetType" json:"asset_type,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Source               string   `protobuf:"bytes,5,opt,name=source" json:"source,omitempty"`
	Owner                string   `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	Private              bool     `protobuf:"varint,7,opt,name=private" json:"private,omitempty"`
	Tags                 []string `protobuf:"bytes,8,rep,name=tags" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssetReq) Reset()         { *m = CreateAssetReq{} }
func (m *CreateAssetReq) String() string { return proto.CompactTextString(m) }
func (*CreateAssetReq) ProtoMessage()    {}
func (*CreateAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_assetproto_89180a27e146566d, []int{0}
}
func (m *CreateAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetReq.Unmarshal(m, b)
}
func (m *CreateAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetReq.Marshal(b, m, deterministic)
}
func (dst *CreateAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetReq.Merge(dst, src)
}
func (m *CreateAssetReq) XXX_Size() int {
	return xxx_messageInfo_CreateAssetReq.Size(m)
}
func (m *CreateAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetReq proto.InternalMessageInfo

func (m *CreateAssetReq) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *CreateAssetReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAssetReq) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *CreateAssetReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateAssetReq) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *CreateAssetReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateAssetReq) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CreateAssetReq) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AssetReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	Private              bool     `protobuf:"varint,4,opt,name=private" json:"private,omitempty"`
	Video                bool     `protobuf:"varint,5,opt,name=video" json:"video,omitempty"`
	Audio                bool     `protobuf:"varint,6,opt,name=audio" json:"audio,omitempty"`
	Image                bool     `protobuf:"varint,7,opt,name=image" json:"image,omitempty"`
	Limit                int32    `protobuf:"varint,8,opt,name=limit" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,9,opt,name=offset" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetReq) Reset()         { *m = AssetReq{} }
func (m *AssetReq) String() string { return proto.CompactTextString(m) }
func (*AssetReq) ProtoMessage()    {}
func (*AssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_assetproto_89180a27e146566d, []int{1}
}
func (m *AssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetReq.Unmarshal(m, b)
}
func (m *AssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetReq.Marshal(b, m, deterministic)
}
func (dst *AssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetReq.Merge(dst, src)
}
func (m *AssetReq) XXX_Size() int {
	return xxx_messageInfo_AssetReq.Size(m)
}
func (m *AssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_AssetReq proto.InternalMessageInfo

func (m *AssetReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssetReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *AssetReq) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AssetReq) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *AssetReq) GetVideo() bool {
	if m != nil {
		return m.Video
	}
	return false
}

func (m *AssetReq) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *AssetReq) GetImage() bool {
	if m != nil {
		return m.Image
	}
	return false
}

func (m *AssetReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AssetReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Asset struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	AssetType            string   `protobuf:"bytes,2,opt,name=asset_type,json=assetType" json:"asset_type,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	Caption              string   `protobuf:"bytes,5,opt,name=caption" json:"caption,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_assetproto_89180a27e146566d, []int{2}
}
func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (dst *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(dst, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Asset) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Asset) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Asset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ListAssetResp struct {
	Count                int32    `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Assets               []*Asset `protobuf:"bytes,2,rep,name=assets" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAssetResp) Reset()         { *m = ListAssetResp{} }
func (m *ListAssetResp) String() string { return proto.CompactTextString(m) }
func (*ListAssetResp) ProtoMessage()    {}
func (*ListAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_assetproto_89180a27e146566d, []int{3}
}
func (m *ListAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAssetResp.Unmarshal(m, b)
}
func (m *ListAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAssetResp.Marshal(b, m, deterministic)
}
func (dst *ListAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAssetResp.Merge(dst, src)
}
func (m *ListAssetResp) XXX_Size() int {
	return xxx_messageInfo_ListAssetResp.Size(m)
}
func (m *ListAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListAssetResp proto.InternalMessageInfo

func (m *ListAssetResp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListAssetResp) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAssetReq)(nil), "assetproto.CreateAssetReq")
	proto.RegisterType((*AssetReq)(nil), "assetproto.AssetReq")
	proto.RegisterType((*Asset)(nil), "assetproto.Asset")
	proto.RegisterType((*ListAssetResp)(nil), "assetproto.ListAssetResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssetServiceClient interface {
	CreateAsset(ctx context.Context, in *CreateAssetReq, opts ...grpc.CallOption) (*ListAssetResp, error)
	GetAsset(ctx context.Context, in *AssetReq, opts ...grpc.CallOption) (*ListAssetResp, error)
	GetMediaLibrary(ctx context.Context, in *AssetReq, opts ...grpc.CallOption) (*ListAssetResp, error)
}

type assetServiceClient struct {
	cc *grpc.ClientConn
}

func NewAssetServiceClient(cc *grpc.ClientConn) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) CreateAsset(ctx context.Context, in *CreateAssetReq, opts ...grpc.CallOption) (*ListAssetResp, error) {
	out := new(ListAssetResp)
	err := c.cc.Invoke(ctx, "/assetproto.AssetService/CreateAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetAsset(ctx context.Context, in *AssetReq, opts ...grpc.CallOption) (*ListAssetResp, error) {
	out := new(ListAssetResp)
	err := c.cc.Invoke(ctx, "/assetproto.AssetService/GetAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetMediaLibrary(ctx context.Context, in *AssetReq, opts ...grpc.CallOption) (*ListAssetResp, error) {
	out := new(ListAssetResp)
	err := c.cc.Invoke(ctx, "/assetproto.AssetService/GetMediaLibrary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
type AssetServiceServer interface {
	CreateAsset(context.Context, *CreateAssetReq) (*ListAssetResp, error)
	GetAsset(context.Context, *AssetReq) (*ListAssetResp, error)
	GetMediaLibrary(context.Context, *AssetReq) (*ListAssetResp, error)
}

func RegisterAssetServiceServer(s *grpc.Server, srv AssetServiceServer) {
	s.RegisterService(&_AssetService_serviceDesc, srv)
}

func _AssetService_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assetproto.AssetService/CreateAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateAsset(ctx, req.(*CreateAssetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assetproto.AssetService/GetAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAsset(ctx, req.(*AssetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetMediaLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetMediaLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assetproto.AssetService/GetMediaLibrary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetMediaLibrary(ctx, req.(*AssetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AssetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "assetproto.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAsset",
			Handler:    _AssetService_CreateAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _AssetService_GetAsset_Handler,
		},
		{
			MethodName: "GetMediaLibrary",
			Handler:    _AssetService_GetMediaLibrary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assetproto.proto",
}

func init() { proto.RegisterFile("assetproto.proto", fileDescriptor_assetproto_89180a27e146566d) }

var fileDescriptor_assetproto_89180a27e146566d = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x6e, 0xd4, 0x30,
	0x18, 0x85, 0x71, 0x32, 0x49, 0x33, 0xff, 0x40, 0x29, 0xd6, 0x08, 0x99, 0x4a, 0x48, 0x51, 0x56,
	0x61, 0xd3, 0x45, 0x59, 0xb3, 0x40, 0x20, 0xba, 0x29, 0x12, 0x32, 0xec, 0x91, 0x9b, 0xfc, 0x1d,
	0x59, 0x6a, 0xc7, 0xc1, 0xf6, 0x0c, 0x9a, 0x9b, 0x70, 0x28, 0x2e, 0x80, 0xb8, 0x0c, 0xf2, 0xef,
	0xa4, 0x49, 0xa8, 0x00, 0x89, 0x4d, 0xe4, 0xf7, 0x39, 0xb6, 0xdf, 0x7b, 0x36, 0x9c, 0x28, 0xe7,
	0xd0, 0x77, 0xd6, 0x78, 0x73, 0x46, 0x5f, 0x0e, 0x23, 0xa9, 0x7e, 0x30, 0x38, 0x7e, 0x63, 0x51,
	0x79, 0x7c, 0x1d, 0xa0, 0xc4, 0x2f, 0x5c, 0xc0, 0x51, 0xa3, 0x3a, 0xaf, 0xcd, 0x56, 0xb0, 0x92,
	0xd5, 0x4b, 0x39, 0x48, 0x5e, 0xc2, 0xaa, 0x45, 0xd7, 0x58, 0x1d, 0x67, 0x13, 0x9a, 0x9d, 0x22,
	0xfe, 0x1c, 0xe2, 0xe6, 0x9f, 0xfd, 0xa1, 0x43, 0x91, 0xd2, 0x0f, 0x4b, 0x22, 0x9f, 0x0e, 0x1d,
	0xf2, 0x13, 0x48, 0x77, 0xf6, 0x46, 0x2c, 0x88, 0x87, 0x21, 0x7f, 0x0a, 0xb9, 0x33, 0x3b, 0xdb,
	0xa0, 0xc8, 0x08, 0xf6, 0x8a, 0xaf, 0x21, 0x33, 0x5f, 0xb7, 0x68, 0x45, 0x4e, 0x38, 0x8a, 0x60,
	0xad, 0xb3, 0x7a, 0xaf, 0x3c, 0x8a, 0xa3, 0x92, 0xd5, 0x85, 0x1c, 0x24, 0xe7, 0xb0, 0xf0, 0x6a,
	0xe3, 0x44, 0x51, 0xa6, 0xf5, 0x52, 0xd2, 0xb8, 0xfa, 0xce, 0xa0, 0xb8, 0x4b, 0x75, 0x0c, 0x89,
	0x6e, 0xfb, 0x40, 0x89, 0x6e, 0x83, 0x15, 0xaf, 0x36, 0x7d, 0x86, 0x30, 0x1c, 0x8f, 0x4c, 0xff,
	0x70, 0xe4, 0x62, 0x7e, 0xe4, 0x1a, 0xb2, 0xbd, 0x6e, 0xd1, 0x90, 0xf3, 0x42, 0x46, 0x11, 0xa8,
	0xda, 0xb5, 0xda, 0x90, 0xf1, 0x42, 0x46, 0x11, 0xa8, 0xbe, 0x55, 0x9b, 0xc1, 0x76, 0x14, 0x81,
	0xde, 0xe8, 0x5b, 0xed, 0x45, 0x51, 0xb2, 0x3a, 0x93, 0x51, 0x84, 0x4a, 0xcc, 0xf5, 0xb5, 0x43,
	0x2f, 0x96, 0x84, 0x7b, 0x55, 0x7d, 0x63, 0x90, 0x51, 0x9c, 0xa1, 0x46, 0x36, 0xd6, 0x38, 0xef,
	0x3d, 0xf9, 0xbd, 0xf7, 0x18, 0x3e, 0xbd, 0x0b, 0x3f, 0xb4, 0xb5, 0x18, 0xdb, 0x9a, 0x5e, 0x7b,
	0xf6, 0xd7, 0x6b, 0xcf, 0xef, 0x5d, 0x7b, 0xf5, 0x01, 0x1e, 0x5d, 0x6a, 0xe7, 0xfb, 0xb2, 0x5d,
	0x17, 0x92, 0x35, 0x66, 0xb7, 0xf5, 0xe4, 0x31, 0x93, 0x51, 0xf0, 0x17, 0x90, 0x93, 0x27, 0x27,
	0x92, 0x32, 0xad, 0x57, 0xe7, 0x4f, 0xce, 0x26, 0x6f, 0x33, 0x2e, 0xee, 0x7f, 0x38, 0xff, 0xc9,
	0xe0, 0x21, 0x91, 0x8f, 0x68, 0xf7, 0xba, 0x41, 0xfe, 0x0e, 0x56, 0x93, 0x77, 0xca, 0x4f, 0xa7,
	0x4b, 0xe7, 0x0f, 0xf8, 0xf4, 0xd9, 0x74, 0x6e, 0xe6, 0xab, 0x7a, 0xc0, 0x5f, 0x41, 0x71, 0x81,
	0x91, 0xf0, 0xf5, 0xfd, 0xf3, 0xff, 0xb5, 0xfc, 0x2d, 0x3c, 0xbe, 0x40, 0xff, 0x1e, 0x5b, 0xad,
	0x2e, 0xf5, 0x95, 0x55, 0xf6, 0xf0, 0x1f, 0xbb, 0x5c, 0xe5, 0x84, 0x5f, 0xfe, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x52, 0xa1, 0xe8, 0xc3, 0x9c, 0x03, 0x00, 0x00,
}